apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: catalog.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catalog-service
                port:
                  number: 80