apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order-container
          image: andreeeiruan/order:1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "300m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: CATALOG_URL
              value: "http://catalog-service"
            - name: INVENTORY_URL
              value: "http://inventory-service"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: order-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50