name: Build and Deploy Catalog API

on:
  push:
    paths:
      - 'apis/catalog/**'
      - '.github/workflows/catalog-api.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apis/catalog
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/catalog:${{ env.SHORT_SHA }}

      - name: Update deployment image tag
        run: |
          sed -i "s|\(image: .*/catalog:\).*|\1${SHORT_SHA}|" apis/catalog/k8s/deployment.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update catalog image tag to ${{ env.SHORT_SHA }}"
          file_pattern: apis/catalog/k8s/deployment.yaml